### ISSUE TITLE
dhall-lsp-server 1.1.x stops working with VSCode LSP Client under the presence of syntax error

### ISSUE THREAD

**Issue by konn** [dhall-lang/dhall-haskell#2418]
Also reported here: https://github.com/dhall-lang/vscode-dhall-lsp-server/issues/38.

# Description
It seems that a simple syntax error makes dhall-lsp-server hang, which makes Dhall Language Support extension almost unusable.
It is particularly annoying that just creating an empty file makes LSP server hang and we MUST reload the entire window to get Dhall LSP to back.

The below is the almost literal copy of https://github.com/dhall-lang/vscode-dhall-lsp-server/issues/38.

## Steps to reproduce
1. Create empty `empty.dhall` and open with VSCode
2. Dhall Client Hangs with Message `The VSCode Dhall Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

## Another reproduction steps
1. Reload the entire workspace if you had followed the above steps.
2. Open `simple.dhall`:

    ```dhall
    let theNumber = 42 in { theNumber }
    ```

3. Insert `:` after `theNumber` and thinks what to be inserted there for a few seconds
4. Client stops working with the error message `The VSCode Dhall Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

### Crash log
<details>
<summary>client log</summary>

```
..Dhall LSP Server has been started..
[Error - 14:06:15] lsp:no handler for:  SInitialized
[Error - 14:06:15] lsp:no handler for:  SWorkspaceDidChangeConfiguration
[Error - 14:06:45] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:45] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:46] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:47] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:48] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:49] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:49] lsp:no handler for:  STextDocumentDidChange
[Error - 14:06:49] lsp:no handler for:  STextDocumentDidChange
[Error - 14:07:15] lsp:no handler for:  STextDocumentDidChange
[Error - 14:07:15] lsp:no handler for:  STextDocumentDidChange
[Error - 14:07:15] lsp:no handler for:  STextDocumentDidChange
dhall-lsp-server: user error (Could not process document links; did not parse.)
Could not process document links; did not parse.
[Info  - 14:07:16] Connection to server got closed. Server will restart.
[Error - 14:07:16] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 14:07:16] lsp:no handler for:  SInitialized
[Error - 14:07:16] lsp:no handler for:  SWorkspaceDidChangeConfiguration
dhall-lsp-server: user error (Could not process document links; did not parse.)
Could not process document links; did not parse.
[Info  - 14:07:16] Connection to server got closed. Server will restart.
[Error - 14:07:16] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 14:07:16] lsp:no handler for:  SInitialized
[Error - 14:07:16] lsp:no handler for:  SWorkspaceDidChangeConfiguration
dhall-lsp-server: user error (Could not process document links; did not parse.)
[Info  - 14:07:16] Connection to server got closed. Server will restart.
[Error - 14:07:16] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 14:07:16] lsp:no handler for:  SInitialized
[Error - 14:07:16] lsp:no handler for:  SWorkspaceDidChangeConfiguration
dhall-lsp-server: user error (Could not process document links; did not parse.)
Could not process document links; did not parse.
[Info  - 14:07:16] Connection to server got closed. Server will restart.
[Error - 14:07:16] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 14:07:16] lsp:no handler for:  SInitialized
[Error - 14:07:16] lsp:no handler for:  SWorkspaceDidChangeConfiguration
dhall-lsp-server: user error (Could not process document links; did not parse.)
Could not process document links; did not parse.
[Error - 14:07:16] Connection to server got closed. Server will not be restarted.
[Error - 14:07:16] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2150:42)
	at LanguageClient.handleConnectionClosed (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-languageclient/lib/client.js:2137:18)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageWriter.fireClose (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/hiromi/.vscode/extensions/dhall.vscode-dhall-lsp-server-0.0.4/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
```

</details>

## Environment
- VSCode: Version: 1.67.1 (Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d)
- Dhall LSP Server:

  ```
  Name: Dhall LSP Server
  Id: dhall.vscode-dhall-lsp-server
  Description: An LSP protocol implementation for the Dhall programming language
  Version: 0.0.4
  Publisher: dhall
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dhall.vscode-dhall-lsp-server
  ```
- macOS Monterey 12.3.1 (21E258)
- dhall-lsp-server 1.1.1 or 1.1.0 (installed via stack install)
  * dhall-lsp-server-1.0.18 seems working with syntactic error.

**Comment by konn** [comment]
Seems related to (or has the same root with) #2411.
